apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ks-project-ingress
spec:
  rules:
  - host: unirep.website
    http:
      paths:
      - path: /ks-auth
        backend:
          serviceName: ks-auth-service
          servicePort: 8080
      - path: /ks-core
        backend:
          serviceName: ks-core-service
          servicePort: 8081
      - path: /ks-analysis
        backend:
          serviceName: ks-analysis-service
          servicePort: 8082
