apiVersion: v1
kind: Service
metadata:
  name: ks-analysis-service
spec:
  selector:
    app: ks-analysis
  ports:
  - port: 8082
    targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: ks-core-service
spec:
  selector:
    app: ks-core
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ks-auth-service
spec:
  selector:
    app: ks-auth
  ports:
  - port: 8080
    targetPort: 8080


