apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks-core
spec:
  selector:
    matchLabels:
      app: ks-core
  template:
    metadata:
      labels:
        app: ks-core
    spec:
      containers:
      - name: ks-core
        image: "mathlimma/ks-core"
        ports:
        - containerPort: 8082
