apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks-auth
spec:
  selector:
    matchLabels:
      app: ks-auth
  template:
    metadata:
      labels:
        app: ks-auth
    spec:
      containers:
      - name: ks-auth
        image: "mathlimma/ks-auth:latest"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
